package com.lgzczs.app.ui.theme

import androidx.compose.ui.graphics.Color

val Primary = Color(0xFF1976D2)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFFD1E4FF)
val OnPrimaryContainer = Color(0xFF001D36)
val Secondary = Color(0xFF535F70)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFFD7E3F7)
val OnSecondaryContainer = Color(0xFF101C2B)
val Tertiary = Color(0xFF6B5778)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFFF2DAFF)
val OnTertiaryContainer = Color(0xFF251431)
val Background = Color(0xFFFDFCFF)
val OnBackground = Color(0xFF1A1C1E)
val Surface = Color(0xFFFDFCFF)
val OnSurface = Color(0xFF1A1C1E)
val SurfaceVariant = Color(0xFFDFE2EB)
val OnSurfaceVariant = Color(0xFF43474E)
val Error = Color(0xFFBA1A1A)
val OnError = Color(0xFFFFFFFF)
val Outline = Color(0xFF73777F)
val InverseSurface = Color(0xFF2F3033)
val InverseOnSurface = Color(0xFFF1F0F4)
val InversePrimary = Color(0xFF9ECAFF)
